swiftlang/swift-docc-plugin

- IntegrationTests/Tests/Utility/XCTestCase+availablePort.swift
A new trunk compiler has been built since SR-15912 was resolved so we can re-enable the preview server test cases that rely on SwiftNIO.
> Re-enable preview server test cases

- README.md
- Sources/SwiftDocCPluginDocumentation/SwiftDocCPlugin.docc/Getting Started with the Swift-DocC Plugin.md
- Sources/SwiftDocCPluginDocumentation/SwiftDocCPlugin.docc/SwiftDocCPlugin.md
Bug/issue #, if applicable: rdar://90124447
Updates documentation throughout to prepare for the 1.0 release of the plugin aligned with Swift 5.6.
Confirm that documentation doesn't contain any references to the `main` branch or the plugin being under active-development and not ready for production use.
> Prepare documentation for 1.0 release

- Sources/SwiftDocCPluginDocumentation/SwiftDocCPlugin.docc/Publishing to GitHub Pages.md
Bug/issue #, if applicable: 
https://forums.swift.org/t/docc-for-private-github-repos/55770/2
Added documentation for github private pages .
For private repos, hosting-base-path is not needed, as each repo is served from its own subdomain. Also the url format for such pages is also different.
Not Applicable
Not Applicable
> Update Documentation For Private Github Pages

- IntegrationTests/Tests/Fixtures/PackageWithSnippets/_Snippets/TestTest.swift
- Sources/Snippets/Parsing/PlainTextSnippetExtractor.swift
- Tests/SwiftDocCPluginUtilitiesTests/SnippetBuildTests.swift
Explanations no longer use the `//!` prefix but a regular,
uninterrupted list of `//` comments.
rdar://95220029
> Snippets: Implement SE-0356 changes to explanation parsing

- Sources/SwiftDocCPluginDocumentation/SwiftDocCPlugin.docc/SwiftDocCPlugin.md
With Swift 5.7, Swift-DocC has support for setting a custom display name in documentation. We can use it here to render the top-level page of the plugin's documentation as "Swift-DocC Plugin" instead of "SwiftDocCPlugin".
> Set a custom display name for the plugin's documentation

- bin/check-source
- bin/test
Expect `SWIFT_DOCC_BRANCH` and `SWIFT_DOCC_RENDER_ARTIFACT_BRANCH` in the
environment. If both are set when running `./bin/test`, clone the respective
repos at those branches and set `DOCC_EXEC` and `DOCC_HTML_DIR` when running the
tests.
Exclude these cloned directories from `./bin/check-source`.
rdar://97294776
> Allow test script to use upstream DocC.

- Plugins/Swift-DocC Preview/SwiftDocCPreview.swift
Windows does not support signal(2).  Instead, use `TerminateProcess` to
terminate the process.  We will not properly handle the termination of
child processes for the preview process, which should be handled by the
construction of a job object that all child processes are attached to
such that when the parent process is terminated, the children will be
properly reaped.  This is required to enable building the plugin on
Windows which is a dependency for swift-syntax.
> Preview: remove use of `signal` on Windows

- Sources/Snippets/Parsing/SnippetParser.swift
Bug/issue: #30 
Allows Documentation to be generated against Xcode 13
N/A
No new tests added, all current tests run and pass, no new functionality added
> Unwrap variables in a way Xcode 13 can be compiled

- IntegrationTests/Tests/DocCArchiveIndexGenerationTests.swift
- IntegrationTests/Tests/Fixtures/PackageWithSnippets/Package.swift
- IntegrationTests/Tests/MixedTargetsTests.swift
- IntegrationTests/Tests/SingleExecutableTargetTests.swift
- IntegrationTests/Tests/SingleLibraryTargetTests.swift
- IntegrationTests/Tests/SingleTestTargetTests.swift
- IntegrationTests/Tests/SnippetDocumentationGenerationTests.swift
- IntegrationTests/Tests/SwiftDocCPreviewTests.swift
- IntegrationTests/Tests/SwiftPMSandboxTests.swift
- IntegrationTests/Tests/TargetWithDocCCatalogTests.swift
- IntegrationTests/Tests/Utility/ConcurrencyRequiringTestCase.swift
- IntegrationTests/Tests/Utility/XCTestCase+swiftPackage.swift
SwiftPM command plugins can only be run when the Swift concurrency libraries are available. For some reason these libraries are no longer available in the macOS used in SwiftCI so this disables those tests after performing a check to see if concurrency is available.
This mirrors the implementation in SwiftPM itself here: https://github.com/apple/swift-package-manager/blob/dd7e9cc6/Sources/SPMTestSupport/Toolchain.swift#L55
> Disable integration tests on macOS to unblock CI

- Package.swift
- Sources/SwiftDocCPluginUtilities/Snippets/SnippetExtractor.swift
- Sources/snippet-extract/SnippetBuildCommand.swift
- Sources/snippet-extract/Utility/SymbolGraph+Snippet.swift
- Tests/SwiftDocCPluginUtilitiesTests/Snippets/SnippetExtractTests.swift
- Tests/SwiftDocCPluginUtilitiesTests/Snippets/SnippetSymbolTests.swift
This does not change the experience for package authors but allows for better integration with other tools that require sandboxing of file access.
rdar://103034070
> Make snippet-extract take individual input/output files instead of a directory

- bin/test
Resolves an issue where CI is failing with:
```
/swift-docc-plugin/swift-docc/Sources/generate-symbol-graph/main.swift:13:18: error: module 'SwiftDocC' was not compiled for testing
@testable import SwiftDocC
~~~~~~~~~~       ^
```
Caused by: https://github.com/apple/swift-docc/pull/447
> Only build the required `docc` executable product in CI

- Sources/snippet-extract/Utility/SymbolGraph+Snippet.swift
- Tests/SwiftDocCPluginUtilitiesTests/Snippets/SnippetSymbolTests.swift
> Prevent adding extra `Snippets` path component when converting to symbol graph symbols

- Plugins/Swift-DocC Convert/SwiftDocCConvert.swift
Bug/issue #, if applicable: #36 
Fix for bug introduced in https://github.com/apple/swift-docc-plugin/commit/5f2e247f5efef4ff8ee603443a9a29225ce9f0e2 refactor, where `SnippetBuilder` had to be refactored to `SnippetExtractor`.
N/A
N/A
> Xcode 13 produces error `Cannot find type 'SnippetBuilder'` in scope

- IntegrationTests/Tests/SnippetDocumentationGenerationTests.swift
- Plugins/SharedPackagePluginExtensions/PackageManager+getSymbolGraphsForDocC.swift
The snippet symbol graph is currently being generated with the changes in e013865138b, however they are not being copied to the correct final destination.
The `snippet-extract` tool now takes input and output *files* instead of directories, however there is still one place in the plugin where we are still treating the output like a directory, so the snippet symbol graph basename path component looks like a directory, and needs additional basenames to put it in the right place with the correct file extension.
rdar://104045850
> Copy snippet symbol graphs to the correct final destination

- Sources/snippet-extract/SnippetBuildCommand.swift
No functional change with this change. This allows the plugin to continue to build in Xcode 13.3.
> Provide initializer for binding in guard for earlier Swift compatibility

- CONTRIBUTING.md
Bug/issue #, if applicable: N/A
This pull-request updates CONTRIBUTING.md: 
- Changes mentions of Swift JIRA to GitHub, consistent with [Swift-DocC repo](https://github.com/apple/swift-docc/blob/main/CONTRIBUTING.md)
- Documents how to use local `swift-docc-plugin` in other Swift packages.
- Documents how to use local `docc` from the plugin.
Related to https://github.com/apple/swift-docc/pull/653 — once @ethan-kusters reviewd that one, I asked if I should clean `swift-docc-plugin` to be consistent as well.
No code changes, so no dependencies.
> Documenting local debug/test workflows in CONTRIBUTING.md

- CONTRIBUTING.md
- Sources/SwiftDocCPluginUtilities/HelpInformation.swift
- Tests/SwiftDocCPluginUtilitiesTests/HelpInformationTests.swift
- Tests/SwiftDocCPluginUtilitiesTests/Test Fixtures/DocCConvertHelpFixture.txt
- Tests/SwiftDocCPluginUtilitiesTests/Test Fixtures/DocCPreviewHelpFixture.txt
Bug/issue #, if applicable: #71
This update the processing of the DocC help text to include all the DocC option groups and not just the last one.
Since there are multiple option groups in recent versions of DocC, the option groups from DocC are prefixed with "DOCC" to distinguish them from the option groups from the plugin.
None.
Compare the output from `docc convert --help` (from a local `main` build or recent main development toolchain) with the output from `swift package plugin generate-documentation -h`.
All DocC options should be included in the plugin help text.
- ~[ ] Updated documentation if necessary~
> Include all DocC help options in the plugin help

- IntegrationTests/Tests/SnippetDocumentationGenerationTests.swift
- IntegrationTests/Tests/SwiftDocCPreviewTests.swift
- IntegrationTests/Tests/Utility/XCTestCase+swiftPackage.swift
Bug/issue #, if applicable: 
This skips any integration test that fail because of rdar://134406349:
```
<unknown>:0: error: unknown argument: '-Xlinker'
<unknown>:0: error: unknown argument: '-rpath'
<unknown>:0: error: unknown argument: '-Xlinker'
```
See https://github.com/swiftlang/swift-docc-plugin/pull/88#issuecomment-2301554564
If we merge this—to unblock current PRs—we will open another PR that reverts this so that we can check when a fix is available in the CI.
None.
None. If the tests pass in the CI, then we know that this works.
- ~[ ] Added tests~ 
- ~[ ] Updated documentation if necessary~ Not applicable
> Disable integration tests that fail because of rdar://134406349

- IntegrationTests/Tests/MixedTargetsTests.swift
- IntegrationTests/Tests/Utility/XCTestCase+swiftPackage.swift
- Plugins/SharedPackagePluginExtensions/PackageManager+getSymbolGraphsForDocC.swift
- Plugins/SharedPackagePluginExtensions/Target+doccArchiveOutputPath.swift
- Plugins/Swift-DocC Convert/SwiftDocCConvert.swift
- Plugins/Swift-DocC Preview/SwiftDocCPreview.swift
- Sources/SwiftDocCPluginUtilities/BuildGraph/DocumentationBuildGraphRunner.swift
- Sources/SwiftDocCPluginUtilities/DocCFeatures.swift
- Sources/SwiftDocCPluginUtilities/ParsedArguments.swift
- Tests/SwiftDocCPluginUtilitiesTests/ParsedArgumentsTests.swift
Bug/issue #, if applicable: 
Support passing a custom `--output-path` value when building documentation for multiple targets.
This is technically unrelated to support for combined documentation archives, but it's more likely that developers will pass a custom output path when building combined documentation for multiple targets.
I implemented this PR in steps:
- First https://github.com/swiftlang/swift-docc-plugin/pull/89/commits/e66ee31902270dc48b3cfeb505ee16ebd24bfbe8 added support for `--output-path` only when building combined documentation.
- Then https://github.com/swiftlang/swift-docc-plugin/pull/89/commits/39d886c10f2bc4deb0f9a077e1f8ae6bb3f0a43a extended that support to non-combined documentation builds as well. 
This is technically a change in behavior—each target will output in …
> Support `--output-path` when building documentation for multiple targets.

- Plugins/SharedPackagePluginExtensions/ArgumentExtractor+extractSpecifiedTargets.swift
- Plugins/SharedPackagePluginExtensions/PackageExtensions.swift
- Plugins/SharedPackagePluginExtensions/PackageManager+getSymbolGraphsForDocC.swift
- Plugins/SharedPackagePluginExtensions/SnippetExtractor+generateSnippetsForTarget.swift
- Plugins/SharedPackagePluginExtensions/Target+defaultSymbolGraphOptions.swift
- Plugins/Swift-DocC Convert/SwiftDocCConvert.swift
- Plugins/Swift-DocC Preview/SwiftDocCPreview.swift
With this change you can now treat C/C++ targets through clang in the same way as Swift. They can be included in generated doccarchive and previewed in the same way.
Update the uses of SwiftSourceModuleTarget to use the more general SourceModuleTarget.
No dependencies on this change. DocC itself can generate documentation for C/C++ symbol graphs.
Git clone a package that has a C target, such as the SwiftPM enabled version of libarchive here and run the docc plugin to generate a preview of its documentation.
Steps:
1. `git clone -b vendor-libarchive https://github.com/cmcgee1024/swiftly.git`
2. `cd swiftly/libarchive`
3. Modify the Package.swift file to point to a version of the swift-docc-plugin that permits documentation to be generated for C targets. Add the following package dependency …
> Allow clang source module targets to be documented using the plugin

- IntegrationTests/Package.swift
- IntegrationTests/Tests/CombinedDocumentationTests.swift
- IntegrationTests/Tests/Fixtures/TargetsWithDependencies/Package.swift
- IntegrationTests/Tests/Fixtures/TargetsWithDependencies/Sources/InnerFirst/SomeFile.swift
- IntegrationTests/Tests/Fixtures/TargetsWithDependencies/Sources/InnerSecond/SomeFile.swift
- IntegrationTests/Tests/Fixtures/TargetsWithDependencies/Sources/NestedInner/SomeFile.swift
- IntegrationTests/Tests/Fixtures/TargetsWithDependencies/Sources/Outer/SomeFile.swift
- Plugins/Swift-DocC Convert/SwiftDocCConvert.swift
- Sources/Snippets/Model/Snippet.swift
- Sources/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArgument.swift
- Sources/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift
- Sources/SwiftDocCPluginUtilities/CommandLineArguments/ParsedPluginArguments.swift
- Sources/SwiftDocCPluginUtilities/DocumentedPluginFlags/DocumentedArgument.swift
- Sources/SwiftDocCPluginUtilities/HelpInformation.swift
- Sources/SwiftDocCPluginUtilities/ParsedArguments.swift
- Sources/snippet-extract/Utility/SymbolGraph+Snippet.swift
- Sources/snippet-extract/Utility/URL+Status.swift
- Tests/SwiftDocCPluginUtilitiesTests/CommandLineArgumentsTests.swift
Bug/issue #, if applicable: #97 
This fixes an issue where the plugin would only pass one `--dependency` value when building combined documentation.
@sofiaromorales and I worked together on the initial fix and made some additional API refinements to the way that the plugin works with command line arguments to make it ensure that an option always has the same behavior at every call site and that an option can't accidentally be used as a flag or vice-versa.
After what Sofía and I worked on,  I made some follow-up changes to use the `Flag` and `Option` types in more places, move the `inverseNames` into `Flag`, and use `CommandLineArguments` for the `docc merge` arguments to avoid that direct `[String]` manipulation.
None.
Build combined documentation for a Swift package where at least one of …
> Fix a bug where targets with multiple dependencies was only passed one dependency

- Sources/SwiftDocCPluginUtilities/BuildGraph/DocumentationBuildGraph.swift
- Sources/SwiftDocCPluginUtilities/FoundationExtensions/SendableMetatypeShim.swift
- bin/check-source
Bug/issue #, if applicable: rdar://152474585
This resolves a few warnings in Swift 6.2 about non-sendable types in isolated closures.
These changes are all in `internal` API, so we don't need to consider API breaking changes.
None.
Build DocC with a Swift 6.2 compiler. There shouldn't be warnings about "capture of non-sendable type in an isolated closure".
- ~[ ] Added tests~
- ~[ ] Updated documentation if necessary~
> Fix warnings in Swift 6.2 about non-sendable types in isolated closures

- IntegrationTests/Tests/Fixtures/LibraryTargetWithExtensionSymbols/Sources/Library/Library.swift
- bin/update-gh-pages-documentation-site
Fixed some simple non-compiling typos in documents and an echo message.
Please let me know if we should have tests for these changes.
Thanks.
> fix: correct multiple typos across the codebase
